<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ConsumableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $seeds = [
            [
                'uuid' => Str::uuid(),
                'sku' => 'SEED-PEA-001',
                'name' => 'Green Pea Seeds',
                'description' => 'High-quality green pea seeds for microgreen production',
                'category' => 'seeds',
                'subcategory' => 'microgreen_seeds',
                'supplier_sku' => 'GP-2024-001',
                'unit_of_measure' => 'grams',
                'unit_cost' => 0.25,
                'current_stock' => 5000,
                'minimum_stock' => 500,
                'reorder_point' => 750,
                'maximum_stock' => 10000,
                'shelf_life_days' => 730,
                'storage_requirements' => 'Cool, dry place. Temperature 10-15°C, humidity below 60%',
                'specifications' => json_encode([
                    'germination_rate' => '95%',
                    'variety' => 'Green Arrow',
                    'origin' => 'USA',
                    'testing_date' => '2024-01-15'
                ]),
                'is_active' => true,
                'requires_lot_tracking' => true,
                'is_organic' => true,
                'is_non_gmo' => true,
                'notes' => 'Excellent for beginners, sweet flavor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'sku' => 'SEED-SUN-001',
                'name' => 'Black Oil Sunflower Seeds',
                'description' => 'Premium sunflower seeds for microgreen cultivation',
                'category' => 'seeds',
                'subcategory' => 'microgreen_seeds',
                'supplier_sku' => 'SF-2024-002',
                'unit_of_measure' => 'grams',
                'unit_cost' => 0.15,
                'current_stock' => 3000,
                'minimum_stock' => 300,
                'reorder_point' => 500,
                'maximum_stock' => 8000,
                'shelf_life_days' => 365,
                'storage_requirements' => 'Cool, dry place. Remove hulls before use.',
                'specifications' => json_encode([
                    'germination_rate' => '90%',
                    'variety' => 'Black Oil',
                    'origin' => 'Canada',
                    'testing_date' => '2024-02-01'
                ]),
                'is_active' => true,
                'requires_lot_tracking' => true,
                'is_organic' => false,
                'is_non_gmo' => true,
                'notes' => 'Nutty flavor, high protein content',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'sku' => 'SEED-RAD-001',
                'name' => 'Red Arrow Radish Seeds',
                'description' => 'Spicy radish seeds for microgreen production',
                'category' => 'seeds',
                'subcategory' => 'microgreen_seeds',
                'supplier_sku' => 'RD-2024-003',
                'unit_of_measure' => 'grams',
                'unit_cost' => 0.35,
                'current_stock' => 2000,
                'minimum_stock' => 200,
                'reorder_point' => 300,
                'maximum_stock' => 5000,
                'shelf_life_days' => 1095,
                'storage_requirements' => 'Cool, dry storage. Seeds are small, handle carefully.',
                'specifications' => json_encode([
                    'germination_rate' => '96%',
                    'variety' => 'Red Arrow',
                    'origin' => 'Netherlands',
                    'testing_date' => '2024-01-20'
                ]),
                'is_active' => true,
                'requires_lot_tracking' => true,
                'is_organic' => true,
                'is_non_gmo' => true,
                'notes' => 'Fast germination, peppery flavor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'sku' => 'SEED-BRO-001',
                'name' => 'Calabrese Broccoli Seeds',
                'description' => 'Nutritious broccoli seeds for microgreen cultivation',
                'category' => 'seeds',
                'subcategory' => 'microgreen_seeds',
                'supplier_sku' => 'BR-2024-001',
                'unit_of_measure' => 'grams',
                'unit_cost' => 0.45,
                'current_stock' => 1500,
                'minimum_stock' => 150,
                'reorder_point' => 250,
                'maximum_stock' => 3000,
                'shelf_life_days' => 1095,
                'storage_requirements' => 'Cool, dry storage. Very small seeds.',
                'specifications' => json_encode([
                    'germination_rate' => '92%',
                    'variety' => 'Calabrese',
                    'origin' => 'Italy',
                    'testing_date' => '2024-02-15'
                ]),
                'is_active' => true,
                'requires_lot_tracking' => true,
                'is_organic' => true,
                'is_non_gmo' => true,
                'notes' => 'High in sulforaphane, mild broccoli flavor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'sku' => 'SEED-ARU-001',
                'name' => 'Roquette Arugula Seeds',
                'description' => 'Peppery arugula seeds for gourmet microgreens',
                'category' => 'seeds',
                'subcategory' => 'microgreen_seeds',
                'supplier_sku' => 'AR-2024-002',
                'unit_of_measure' => 'grams',
                'unit_cost' => 0.55,
                'current_stock' => 1200,
                'minimum_stock' => 120,
                'reorder_point' => 200,
                'maximum_stock' => 2500,
                'shelf_life_days' => 1095,
                'storage_requirements' => 'Cool, dry storage. Avoid moisture.',
                'specifications' => json_encode([
                    'germination_rate' => '94%',
                    'variety' => 'Roquette',
                    'origin' => 'France',
                    'testing_date' => '2024-01-10'
                ]),
                'is_active' => true,
                'requires_lot_tracking' => true,
                'is_organic' => true,
                'is_non_gmo' => true,
                'notes' => 'Spicy, peppery flavor. Great for salads.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'sku' => 'SEED-KAL-001',
                'name' => 'Red Russian Kale Seeds',
                'description' => 'Colorful kale seeds for nutritious microgreens',
                'category' => 'seeds',
                'subcategory' => 'microgreen_seeds',
                'supplier_sku' => 'KL-2024-001',
                'unit_of_measure' => 'grams',
                'unit_cost' => 0.40,
                'current_stock' => 1800,
                'minimum_stock' => 180,
                'reorder_point' => 300,
                'maximum_stock' => 4000,
                'shelf_life_days' => 1095,
                'storage_requirements' => 'Cool, dry storage.',
                'specifications' => json_encode([
                    'germination_rate' => '91%',
                    'variety' => 'Red Russian',
                    'origin' => 'USA',
                    'testing_date' => '2024-02-01'
                ]),
                'is_active' => true,
                'requires_lot_tracking' => true,
                'is_organic' => true,
                'is_non_gmo' => true,
                'notes' => 'Beautiful red stems, mild kale flavor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'sku' => 'SEED-MUS-001',
                'name' => 'Red Giant Mustard Seeds',
                'description' => 'Spicy mustard seeds with beautiful purple leaves',
                'category' => 'seeds',
                'subcategory' => 'microgreen_seeds',
                'supplier_sku' => 'MU-2024-002',
                'unit_of_measure' => 'grams',
                'unit_cost' => 0.50,
                'current_stock' => 1000,
                'minimum_stock' => 100,
                'reorder_point' => 150,
                'maximum_stock' => 2000,
                'shelf_life_days' => 1095,
                'storage_requirements' => 'Cool, dry storage.',
                'specifications' => json_encode([
                    'germination_rate' => '95%',
                    'variety' => 'Red Giant',
                    'origin' => 'Japan',
                    'testing_date' => '2024-01-25'
                ]),
                'is_active' => true,
                'requires_lot_tracking' => true,
                'is_organic' => false,
                'is_non_gmo' => true,
                'notes' => 'Spicy mustard flavor, striking purple color',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'sku' => 'SEED-BEE-001',
                'name' => 'Bulls Blood Beet Seeds',
                'description' => 'Deep red beet seeds for colorful microgreens',
                'category' => 'seeds',
                'subcategory' => 'microgreen_seeds',
                'supplier_sku' => 'BT-2024-001',
                'unit_of_measure' => 'grams',
                'unit_cost' => 0.30,
                'current_stock' => 2500,
                'minimum_stock' => 250,
                'reorder_point' => 400,
                'maximum_stock' => 5000,
                'shelf_life_days' => 1460,
                'storage_requirements' => 'Cool, dry storage. Seeds are actually clusters.',
                'specifications' => json_encode([
                    'germination_rate' => '88%',
                    'variety' => 'Bulls Blood',
                    'origin' => 'USA',
                    'testing_date' => '2024-02-10'
                ]),
                'is_active' => true,
                'requires_lot_tracking' => true,
                'is_organic' => true,
                'is_non_gmo' => true,
                'notes' => 'Sweet, earthy flavor with beautiful red color',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'sku' => 'SEED-WGR-001',
                'name' => 'Hard Red Winter Wheat',
                'description' => 'Premium wheat berries for wheatgrass production',
                'category' => 'seeds',
                'subcategory' => 'microgreen_seeds',
                'supplier_sku' => 'WG-2024-001',
                'unit_of_measure' => 'grams',
                'unit_cost' => 0.08,
                'current_stock' => 10000,
                'minimum_stock' => 1000,
                'reorder_point' => 1500,
                'maximum_stock' => 25000,
                'shelf_life_days' => 365,
                'storage_requirements' => 'Cool, dry storage in sealed containers.',
                'specifications' => json_encode([
                    'germination_rate' => '93%',
                    'variety' => 'Hard Red Winter',
                    'origin' => 'Kansas, USA',
                    'testing_date' => '2024-01-30'
                ]),
                'is_active' => true,
                'requires_lot_tracking' => false,
                'is_organic' => true,
                'is_non_gmo' => true,
                'notes' => 'Primarily for juicing, sweet grassy flavor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'sku' => 'SEED-CIL-001',
                'name' => 'Slow Bolt Cilantro Seeds',
                'description' => 'Aromatic cilantro seeds for herb microgreens',
                'category' => 'seeds',
                'subcategory' => 'herb_seeds',
                'supplier_sku' => 'CL-2024-001',
                'unit_of_measure' => 'grams',
                'unit_cost' => 0.60,
                'current_stock' => 800,
                'minimum_stock' => 80,
                'reorder_point' => 120,
                'maximum_stock' => 1500,
                'shelf_life_days' => 1095,
                'storage_requirements' => 'Cool, dry storage. Crush lightly before soaking.',
                'specifications' => json_encode([
                    'germination_rate' => '85%',
                    'variety' => 'Slow Bolt',
                    'origin' => 'India',
                    'testing_date' => '2024-02-05'
                ]),
                'is_active' => true,
                'requires_lot_tracking' => true,
                'is_organic' => true,
                'is_non_gmo' => true,
                'notes' => 'Intense cilantro flavor, longer germination time',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($seeds as $seed) {
            DB::table('consumables')->insert($seed);
        }

        $this->command->info('Created ' . count($seeds) . ' seed varieties');
    }
}